---
- name: Deploy go modules
  hosts: app
  tasks:
    - name: Creates directory
      file:
        path: /app
        state: directory
        owner: devops
        group: devops

    - name: Copy artifacts
      copy:
        src: online_shop
        dest: /app/online_shop
        owner: devops
        group: devops
        mode: 755

    - name: Create systemd service
      template:
        src: shop_service.j2
        dest:  /etc/systemd/system/multi-user.target.wants/shop.service

    - name: Restart service
      systemd:
        name: shop
        daemon_reload: yes
        state: restarted