- name: Start container
  hosts: app
  tasks:
  - name: Restart a container
    docker_container:
      name: "{{ app_name }}"
      image: "{{ image_name }}"
      state: started
      restart: yes
      ports:
        - "3000:3000"